name: one_click
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  base_mykiot:
    git:
      url: https://github.com/locidtinc/base_project.git

  flutter_bloc: ^8.1.3
  get_it: ^7.6.7
  injectable: ^2.3.2
  cupertino_icons: ^1.0.6
  json_annotation: ^4.8.1
  freezed_annotation: ^2.2.0
  freezed: ^2.4.1
  # async: ^2.10.0
  auto_route: ^7.8.4

  equatable: ^2.0.6
  intl:
  dotted_border: 2.1.0
  flutter_switch: 0.3.2
  dropdown_button2: 2.3.9
  image_picker: ^1.0.7
  # qr_code_scanner: ^1.0.1
  qr_code_scanner_plus: ^2.0.6
  pinput: ^5.0.1
  qr_flutter: ^4.1.0
  shimmer: ^3.0.0
  #svg flutter
  flutter_svg: ^1.1.6
  # expandable
  expandable: ^5.0.1
  # api request http client
  dio: ^5.4.0
  # input tags
  textfield_tags: ^3.0.1
  # storage for simple data
  shared_preferences: ^2.3.3
  #google maps
  google_maps_flutter: ^2.5.0
  geocoding: ^2.1.1
  dotted_line: ^3.1.0
  #notification
  flutter_local_notifications: ^17.2.4
  # firebase_core
  firebase_core: ^2.15.1
  # firebase_messaging
  firebase_messaging: ^14.6.6
  # firebase_analytics:
  #firebase_database
  firebase_database: ^10.5.7
  # flutter_google_places: ^0.3.0
  # google_maps_webservice: ^0.0.19
  share_plus: ^10.0.0
  path_provider: ^2.0.15
  #search_bar
  material_floating_search_bar_2: ^0.5.0
  #geolocator
  geolocator: ^13.0.2
  # unorm_dart: ^0.2.0
  # package_info_plus: ^4.2.0
  watcher: ^1.1.0
  cached_network_image: ^3.3.1
  # video_player: ^2.8.5
  syncfusion_flutter_maps: ^27.1.58
  curl_logger_dio_interceptor: ^1.0.0
  bloc: ^8.1.4
  url_launcher: ^6.3.0
  currency_text_input_formatter: ^2.3.0
  flutter_localizations:
    sdk: flutter
  calendar_date_picker2: 1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  injectable_generator: ^2.1.5
  json_serializable: ^6.6.2
  auto_route_generator: ^7.1.1
  hive_generator: ^2.0.0
  flutter_lints: ^2.0.0
  flutter_gen_runner: 5.3.1

  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/imgs/logo.png"
  adaptive_icon_background: "#191919"

flutter_assets:
  assets_path: assets/
  output_path: lib/gen/
  filename: assets.dart
  field_prefix:
    from: assets
    to:
  classname: MyAssets

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/imgs/
    - assets/imgs/noti/
    - assets/icons/
    - assets/icons/login/
    - assets/icons/bottom_bar/

  fonts:
    - family: FaPro
      fonts:
        - asset: assets/fonts/fa/v6-Pro-Thin-100.otf
          weight: 100
        - asset: assets/fonts/fa/v6-Pro-Light-300.otf
          weight: 300
        - asset: assets/fonts/fa/v6-Pro-Regular-400.otf
          weight: 400
        - asset: assets/fonts/fa/v6-Pro-Solid-900.otf
          weight: 900

    - family: FaSharp
      fonts:
        - asset: assets/fonts/fa/v6-Sharp-Thin-100.otf
          weight: 100
        - asset: assets/fonts/fa/v6-Sharp-Light-300.otf
          weight: 300
        - asset: assets/fonts/fa/v6-Sharp-Regular-400.otf
          weight: 400
        - asset: assets/fonts/fa/v6-Sharp-Solid-900.otf
          weight: 900

    - family: FaClassic
      fonts:
        - asset: assets/fonts/fa/fa-thin-100.ttf
          weight: 100
        - asset: assets/fonts/fa/fa-light-300.ttf
          weight: 300
        - asset: assets/fonts/fa/fa-regular-400.ttf
          weight: 400
        - asset: assets/fonts/fa/fa-solid-900.ttf
          weight: 900

    - family: FaBrand
      fonts:
        - asset: assets/fonts/fa/v6-Brands-Regular-400.otf

    - family: FaDoutone
      fonts:
        - asset: assets/fonts/fa/v6-Duotone-Solid-900.otf
